### ISSUE TITLE
does this work with the starwars BB-8 model?

### ISSUE THREAD

**Issue by diclophis** [hybridgroup/artoo-sphero#30]

**Comment by ZachBeta** [comment]
I just purchased a BB-8 and am currently having trouble pairing my laptop with the device. The documentation is a bit sparse so I can't tell if it's the BB-8 being significantly different or if it's me misunderstanding the docs.

TLDR: I have no idea, but I want to know too.

**Comment by ZachBeta** [comment]
From what I can tell a vanilla sphero can be shaken to pair with bluetooth. The BB-8 does not go into pairing mode by shaking it as far as I can tell.

I do not see it listed as a bluetooth device on my MacBook Air, which makes it kind of a nonstarter. It seems to show up under bluetooth devices on my phone, but will not respond to a pairing request. It only pairs when in the app.

While it lists its MAC Address under its settings page, I cannot see it listed as discoverable, and cannot connect to an arbitrary address in OSX from what I can tell.

So far it has been impossible to pair from my laptop and thus impossible to set up with artoo-sphero.

YMMV, but I'm going to return it to get a vanilla sphero. I'm much more interested in programming a little sphere robot than I am with neat decals, a cute headpiece on top, and a heavily branded phone app.

![I am dissapoint](http://i.kinja-img.com/gawker-media/image/upload/s--sFvebq-l--/1430491237129766546.jpg)

**Comment by d0nd3r3k** [comment]
Check this out (https://www.npmjs.com/package/sphero) worked with my BB-8 unit!
